### ISSUE TITLE
StartDate / EndDate Conflict

### ISSUE THREAD

**Issue by gordonheitman** [bschooled/Move-FromPurges.ps1#2]
I had a scenario where I set the startdate to 12-01-2017 and the enddate was set to 02-13-2018.  I got the error message;

You cannot specify a Start Date that is after your End Date: Please Run Again

Resetting the startdate to 01-01-2017 and leaving the enddate set to 02-13-2018 works.  I think it may have something to do with using 12 in the startdate and 02 in the enddate.

**Comment by bschooled** [comment]
Hmm interesting, it's likely a formatting issue, as I actually take whatever the user puts in the date, and try to put it into a standard datatime format that is understood by EWS. It should be relatively easy to fix, but I have some upcoming more major changes to the code to make it more secure (Multi-factor support), as well as some additional features to be able to move not just Purges but other folders as well.

**Comment by bschooled** [comment]
Gordon, the issue should be fixed, I took a look and committed the changes. Go ahead and download the latest script and the date time issues should be okay.
